api_platform:
    title: 'API - Librairie'
    description: 'Beaucoup de livres'
    version: '1.0.0'
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        csv: [ 'text/csv' ]
    defaults:
        pagination_enabled: true
        pagination_client_items_per_page: true
        pagination_items_per_page: 20
        pagination_maximum_items_per_page: 100
        format: jsonld
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
