api_platform:
    title: 'API - Librairie'
    description: 'Beaucoup de livres'
    version: '1.0.0'
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        csv: [ 'text/csv' ]
    defaults:
        format: jsonld
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
